# Generated by Django 5.0.7 on 2024-07-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_aluno_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
